apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nongchukya

resources:
  - rollout.yaml
  - service-stable.yaml
  - service-preview.yaml

images:
  - name: sangwon0410/nongchukya-backend
    newTag: latest
