apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  namespace: nongchukya
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: app
          image: sangwon0410/nongchukya-frontend:latest  #오버레이에서 tag 교체
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 20
            periodSeconds: 10
  strategy:
    blueGreen:
      activeService: frontend-stable
      previewService: frontend-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
