apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:                 # ← overlay에서 blue/green으로 패치함
    app: frontend
    color: blue
  ports:
  - name: http
    port: 80
    targetPort: 80
