---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: default
spec:
  encryptedData:
    JWT_SECRET: AgB/XjQGlnPlSYG8s8di+LFBbmXKHP0MOT79KJc5w+/T8BnNcXptpy5rQsnYYtoIQulCBiUqyChyVxMrlVMDQDpD9FsoPP2M/8e3HowCghZSaPvvcSBxzIBOJ672XgUHdvo5yxcuz0p6J2j0rqRq3Q2ge0tGX0ErV1XGJeZLKnCI2XoA6Lfqb0xqey/PVYEU6bVt7/PEh728tfIbx87zucef67JB4EWL2XdwJ3PoXUGQw7d6vXhaBnwjvWYEhj8vhE0YfwjzJpTv9jy0JCc1JseKDVBT4jypUtANoqLTEj3GBXx6ewL9HeRG90CIE2tfmAsL3lu+zSo3hgEn6/4LdfO2SL3/qangI0FKMJa7hE1Wfb+HHRIL5kUDja+o2B0Z+Bq21eEykzT5acCpRdY+evoGs/97i+QLL8l7Vk1JPJurtEJv6q5bm0y4zot1aNMaOg3j/VlIi8frwb6qboAFz/bgVt6A+NiDHxBsrl5FqLTds1w4wBmdHGN/q+4q8qd0Xqk7brzdXCla2cX0Of5xa3njsk2ivsgU9vGRwdEbTHsyxH4PfiNDwyHw+i4t0NWuzRRxSdGekphO/b18iLVzYKISIVP6ckakZoTaHGcgU+B1ZFhx9omXlfsgOaetcsladPtpK3X+4G8IHu0x2yNCPeHfnGU+KIb8sSWooHp/E+ixdOpgauHVqsUfuPSap8bOIB4cmmLBE3jKEapukOH94EU3I8T+FUbsyB1ZovXX6gEJLA==
  template:
    metadata:
      name: backend-secret
      namespace: default
