apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
spec:
  template:
    spec:
      containers:
      - name: app
        envFrom:
        - secretRef:
            name: backend-secret
