apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-green
spec:
  template:
    spec:
      containers:
      - name: app
        envFrom:
          - configMapRef:
              name: backend-config
          - secretRef:
              name: backend-secret
        env:
          - name: JAVA_TOOL_OPTIONS
            value: "-Dspring.profiles.active=docker"
        args:
          - "--spring.profiles.active=docker"
