apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
spec:
  template:
    spec:
      containers:
      - name: app
        envFrom:
          - configMapRef:
              name: backend-config
          - secretRef:
              name: backend-secret
        args:
          - "--spring.profiles.active=docker"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "docker"
          - name: JAVA_TOOL_OPTIONS
            value: "-Dspring.profiles.active=docker"
        
